apiVersion: integration/v1
kind: Step
name: user-get-by-id
version: 1
summary: PagerDuty User Get By ID Step

description: |
  This step gets user details from PagerDuty by their PagerDuty ID

schemas:
  spec:
    source: file
    file: spec.schema.json

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/pagerduty-step-user-get-by-id

schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    $schema: 'http://json-schema.org/draft-07/schema#'
    type: object
    properties:
      response:
        type: string
    required: [response]
