apiVersion: integration/v1
kind: Integration
name: pagerduty
channel: alpha
version: v20200522
summary: PagerDuty
license: Apache-2.0
homepage: https://github.com/relay-integrations/relay-pagerduty

description: |
  PagerDuty is an incident management platform that provides reliable notifications, automatic escalations, on-call scheduling, and other functionality to help teams detect and fix infrastructure problems quickly.

owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com

tags:
  - incident response
  - rto
