apiVersion: container/v1
kind: StepContainer
name: pagerduty-trigger-incident-triggered
title: PagerDuty incident triggered
description: >
  This trigger fires when a PagerDuty incident is triggered for the first time.
images:
  base:
    template: Dockerfile.tpl
